module.exports = {
  addClass: require('./addClass'),
  attr: require('./attr'),
  data: require('./data'),
  hasClass: require('./hasClass'),
  height: require('./height'),
  hide: require('./hide'),
  html: require('./html'),
  remove: require('./remove'),
  removeClass: require('./removeClass'),
  select: require('./select'),
  setAttr: require('./setAttr'),
  setData: require('./setData'),
  setHtml: require('./setHtml'),
  setText: require('./setText'),
  setVal: require('./setVal'),
  show: require('./show'),
  style: require('./style'),
  text: require('./text'),
  toggleClass: require('./toggleClass'),
  val: require('./val'),
  vendor: require('./vendor'),
  width: require('./width')
}